<?php
declare(strict_types=1);

/**
 * File: edit.phtml
 *
 * @copyright Copyright (C) 2023 Algomaps (https://algomaps.com)
 */

use Algolytics\AlgoIntegration\ViewModel\CustomerAddress;
use Algolytics\AlgoIntegration\ViewModel\StoreCode;
use Magento\Customer\Block\Address\Edit;
use Magento\Customer\Block\Widget\Company;
use Magento\Customer\Block\Widget\Fax;
use Magento\Customer\Block\Widget\Telephone;
use Magento\Customer\ViewModel\Address;
use Magento\Customer\ViewModel\Address\RegionProvider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Edit $block */
/** @var Address $viewModel */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var RegionProvider $regionProvider */
$viewModel = $block->getViewModel();
$regionProvider = $block->getRegionProvider();
/** @var CustomerAddress $customerAddressViewModel */
$customerAddressViewModel = $block->getData('customer_address_view_model');
$company = $block->getLayout()->createBlock(Company::class);
$telephone = $block->getLayout()->createBlock(Telephone::class);
$fax = $block->getLayout()->createBlock(Fax::class);
$country_id = $block->getAttributeData()->getFrontendLabel('country_id');
$street = $block->getAttributeData()->getFrontendLabel('street');
$city = $block->getAttributeData()->getFrontendLabel('city');
$region = $block->getAttributeData()->getFrontendLabel('region');
$selectRegion = 'Please select a region, state or province.';
$displayAll = $block->getConfig('general/region/display_all');
$vatidValidationClass = $viewModel->addressGetAttributeValidationClass('vat_id');
$cityValidationClass = $viewModel->addressGetAttributeValidationClass('city');
$postcodeValidationClass_value = $viewModel->addressGetAttributeValidationClass('postcode');
$postcodeValidationClass = $postcodeValidationClass_value;
$streetValidationClass = $viewModel->addressGetAttributeValidationClass('street');
$streetValidationClassNotRequired = $streetValidationClass !== null ?
    trim(str_replace('required-entry', '', $streetValidationClass)) : '';
$regionValidationClass = $viewModel->addressGetAttributeValidationClass('region');

$streetLabels = [
    __('Street'),
    __('Building Number'),
    __('Apartment Number')
]
?>
<form class="form-address-edit"
      action="<?= $escaper->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Contact Information')) ?></span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getNameBlockHtml() ?>

        <?php if ($company->isEnabled()): ?>
            <?= $company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
        <?php endif ?>

        <?php if ($telephone->isEnabled()): ?>
            <?= $telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
        <?php endif ?>

        <?php if ($fax->isEnabled()): ?>
            <?= $fax->setFax($block->getAddress()->getFax())->toHtml() ?>
        <?php endif ?>

    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Address')) ?></span></legend><br>
        <?php if ($viewModel->addressIsVatAttributeVisible()): ?>
            <div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           class="input-text <?= $escaper->escapeHtmlAttr($vatidValidationClass) ?>"
                           id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field country required">
            <label class="label" for="country">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
            </label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id">
                <span><?= /* @noEscape */ $region ?></span>
            </label>
            <div class="control">
                <select id="region_id" name="region_id"
                        title="<?= /* @noEscape */ $region ?>"
                        class="validate-select region_id"
                    <?= /* @noEscape */ !$displayAll ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $escaper->escapeHtml(__($selectRegion)) ?></option>
                </select>
                <input type="text"
                       id="region"
                       name="region"
                       value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"
                       title="<?= /* @noEscape */ $region ?>"
                       class="input-text validate-not-number-first
                        <?= $escaper->escapeHtmlAttr($regionValidationClass) ?>"
                    <?= !$displayAll ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <?php if ($customerAddressViewModel->isOneFieldActive()): ?>
        <div class="field findAddress required">
            <label class="label" for="findAddress">
                <span><?= /* @noEscape */ __('Find address') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="findAddress"
                       value=""
                       title="<?= $escaper->escapeHtmlAttr(__('Find address')) ?>"
                       class="input-text"
                       id="findAddress"
                >
            </div>
        </div>
        <?php endif; ?>
        <div class="field city required">
            <label class="label" for="city">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="city"
                       value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                       class="input-text <?= $escaper->escapeHtmlAttr($cityValidationClass) ?>"
                       id="city"
                       >
            </div>
        </div>
        <div class="field street required">
            <label for="street_1" class="label"><span><?= /* @noEscape */ $streetLabels[0] ?></span></label>
            <div class="control">
                <input type="text"
                       name="street[0]"
                       value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= /* @noEscape */ $street ?>"
                       id="street_1"
                       class="input-text <?= $escaper->escapeHtmlAttr($streetValidationClass) ?>"
                      />
            </div>
        </div>

        <?php for ($i = 1, $n = $viewModel->addressGetStreetLines(); $i < $n; $i++): ?>
            <div class="field">
                <label class="label" for="street_<?= /* @noEscape */ $i + 1 ?>">
                    <span><?= $escaper->escapeHtml($streetLabels[$i] ?? __('Street Address: Line %1', $i + 1)) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="street[<?= /* @noEscape */ $i ?>]"
                           value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($i + 1)) ?>"
                           title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $i + 1)) ?>"
                           id="street_<?= /* @noEscape */ $i + 1 ?>"
                           class="input-text
                                        <?= $escaper->escapeHtmlAttr($streetValidationClassNotRequired) ?>"

                          <?php if ($i === 2): ?>

                          <?php endif; ?>>
                </div>
            </div>
        <?php endfor; ?>

        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                       id="zip"
                       class="input-text validate-zip-international
                        <?= $escaper->escapeHtmlAttr($postcodeValidationClass) ?>">
                <div role="alert" class="message warning">
                    <span></span>
                </div>
                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div.message.warning') ?>
            </div>
        </div>

        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info">
                <span><?= $escaper->escapeHtml(__("It's a default billing address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                <label class="label" for="primary_billing">
                    <span><?= $escaper->escapeHtml(__('Use as my default billing address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info">
                <span><?= $escaper->escapeHtml(__("It's a default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                <label class="label" for="primary_shipping">
                    <span><?= $escaper->escapeHtml(__('Use as my default shipping address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    disabled="disabled"
                    title="<?= $escaper->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $escaper->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/javascript">
    window.checkoutConfig = {storeCode:'<?= $customerAddressViewModel->getStoreCode() ?>'};
</script>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes() ?>
            }
        },
        "#country": {
            "directoryRegionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $displayAll ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $regionProvider->getRegionJson(); ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $viewModel->dataGetCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php if ($customerAddressViewModel->isOneFieldActive()): ?>
<script type="text/x-magento-init">
    {
        "#findAddress": {
            "algolyticsOneFieldAutocomplete": {}
        }
    }
</script>
<?php endif; ?>
<?php if ($customerAddressViewModel->isActive()): ?>
    <script type="text/x-magento-init">
        {
            "#city": {
                "algolyticsCityAutocomplete": {}
            },
            "#street_1": {
                "algolyticsStreetAutocomplete": {}
            },
            "#street_2": {
                "algolyticsBuildingNumberAutocomplete": {}
            }
        }
    </script>
<?php endif; ?>
